/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewStaff;

import ConnectionDatabase.ConnectDB;

import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;

public class CheckInForm extends javax.swing.JFrame {

    ConnectDB cn = new ConnectDB();

    public CheckInForm() {
        initComponents();
        findRoomByType();
        txtDateCheckIn.setDateFormatString("yyyy-MM-dd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCheckIn = new javax.swing.JButton();
        btnCheckIn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCusPhoneNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CbGender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCusID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDateCheckIn = new com.toedter.calendar.JDateChooser();
        btnUpdateTime = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        CbRoomID = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtRoomPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CbRoomType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        btnCheckIn.setBackground(new java.awt.Color(255, 204, 102));
        btnCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/check-in.png"))); // NOI18N
        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnCheckIn1.setBackground(new java.awt.Color(255, 204, 102));
        btnCheckIn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCheckIn1.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckIn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circular.png"))); // NOI18N
        btnCheckIn1.setText("Refresh");
        btnCheckIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckIn1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Customer Name");

        txtCusName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Phone Number");

        txtCusPhoneNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCusPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusPhoneNumActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Sex");

        CbGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("ID");

        txtCusID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("CheckIn Date(Today)");

        btnUpdateTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateTime.setForeground(new java.awt.Color(0, 102, 102));
        btnUpdateTime.setText("Cập Nhật Ngày");
        btnUpdateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(txtCusName)
                    .addComponent(txtCusPhoneNum)
                    .addComponent(CbGender, 0, 238, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(txtCusID)
                        .addComponent(jLabel8)
                        .addComponent(txtDateCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUpdateTime, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCusPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room rental details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Room ID");

        CbRoomID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CbRoomID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbRoomIDActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Room Price");
        jLabel11.setToolTipText("");

        txtRoomPrice.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Room Type");

        CbRoomType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Room", "Double Room", "VIP Room", "Family Room" }));
        CbRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbRoomTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRoomPrice)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(CbRoomID, 0, 224, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(CbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(txtRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/check-in.png"))); // NOI18N
        jLabel1.setText("Đăng Ký Phòng");

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCheckIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCheckIn))
                                .addGap(51, 51, 51))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 65, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnClose))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnCheckIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateTimeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateTimeActionPerformed
        // TODO add your handling code here:

        updateDate();
    }// GEN-LAST:event_btnUpdateTimeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCloseActionPerformed
        Main frm = new Main();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnCloseActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {
        // GEN-FIRST:event_btnCheckInActionPerformed
        String cusID = txtCusID.getText();
        String cusName = txtCusName.getText();
        String cusPhoneNum = txtCusPhoneNum.getText();
        String cusSex = (CbGender.getSelectedItem() != null) ? CbGender.getSelectedItem().toString() : "";
        String roomID = (CbRoomID.getSelectedItem() != null) ? CbRoomID.getSelectedItem().toString() : "";

        if (cusID.isEmpty() || cusName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Not enough information!");
            return;
        }

        try (Connection conn = cn.getConnection()) {
            String sql = "SELECT * FROM Customer WHERE CusID = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, cusID);
            ResultSet rsCustomer = pstmt.executeQuery();

            if (!rsCustomer.next()) {
                String sql_Customer = "INSERT INTO Customer (CusID, CusName, CusPhone, CusGender) VALUES (?, ?, ?, ?)";
                PreparedStatement ps_customer = conn.prepareStatement(sql_Customer);
                ps_customer.setString(1, cusID);
                ps_customer.setString(2, cusName);
                ps_customer.setString(3, cusPhoneNum);
                ps_customer.setString(4, cusSex);
                ps_customer.executeUpdate();
            } else {
                JOptionPane.showMessageDialog(this, "Customer already exists!");
            }

            String sql_Enroll = "INSERT INTO Enroll (EnrollID, CusID, RoomID,CheckInDate) VALUES (?, ?, ?, ?)";
            PreparedStatement ps_enroll = conn.prepareStatement(sql_Enroll);
            ps_enroll.setString(2, cusID);
            ps_enroll.setString(3, roomID);

            java.util.Date date = txtDateCheckIn.getDate();
            if (date != null) {
                java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                ps_enroll.setDate(4, sqlDate);
                ps_enroll.setString(1, cusID + "_" + roomID + "_" + sqlDate.toString());
            } else {
                ps_enroll.setNull(4, java.sql.Types.DATE);
            }

            if (ps_enroll.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Check In Successfully!");
                updateRoomStatus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }// GEN-LAST:event_btnCheckInActionPerformed

    private void btnCheckIn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCheckIn1ActionPerformed
        CheckInForm frm = new CheckInForm();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnCheckIn1ActionPerformed

    private void CbRoomIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CbRoomIDActionPerformed
        // TODO add your handling code here:
        addPrice();
    }// GEN-LAST:event_CbRoomIDActionPerformed

    private void CbRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CbRoomTypeActionPerformed
        // TODO add your handling code here:
        findRoomByType();
        addPrice();
    }// GEN-LAST:event_CbRoomTypeActionPerformed

    private void txtCusPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCusPhoneNumActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCusPhoneNumActionPerformed

    private void updateRoomStatus() {
        String selectValueID = CbRoomID.getSelectedItem().toString();
        String sql = "UPDATE Room SET RoomStatus = 'Booked' WHERE RoomID = ?";

        try (Connection conn = cn.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, selectValueID);
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected <= 0) {
                JOptionPane.showMessageDialog(this, "Can't update!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void findRoomByType() {
        String selectValueType = CbRoomType.getSelectedItem().toString();
        String sql = "SELECT RoomID FROM Room WHERE RoomType = ? AND RoomStatus = 'Not Booked'";

        try (Connection conn = cn.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, selectValueType);
            ResultSet rs = ps.executeQuery();

            CbRoomID.removeAllItems();
            while (rs.next()) {
                CbRoomID.addItem(rs.getString("RoomID"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateDate() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Calendar currentDate = Calendar.getInstance();
            String formattedDate = sdf.format(currentDate.getTime());
            txtDateCheckIn.setDateFormatString("yyyy-MM-dd");
            txtDateCheckIn.setDate(sdf.parse(formattedDate));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void addPrice() {
        String selectValueID = (CbRoomID.getSelectedItem() != null) ? CbRoomID.getSelectedItem().toString() : "";
        String sql_price = "SELECT RoomPrice FROM Room WHERE RoomID = ?";

        try (Connection conn = cn.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql_price)) {

            ps.setString(1, selectValueID);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                txtRoomPrice.setText(rs.getString("RoomPrice"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckInForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckInForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckInForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckInForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckInForm frm = new CheckInForm();
                frm.setLocationRelativeTo(null);
                frm.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbGender;
    private javax.swing.JComboBox<String> CbRoomID;
    private javax.swing.JComboBox<String> CbRoomType;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckIn1;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpdateTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtCusPhoneNum;
    private com.toedter.calendar.JDateChooser txtDateCheckIn;
    private javax.swing.JTextField txtRoomPrice;
    // End of variables declaration//GEN-END:variables
}
